# Exportando do DataFrame para um csv

### Depois de modificar um DataFrame, ou até criar um, muitas vezes podemos exportar esse dataframe para um csv

No pandas, isso é bem simples:

dataframe.to_csv('nome_do_arquivo.csv', sep=',')

### Lendo um DataFrame, modificando ele e exportando

In [1]:
import pandas as pd
#importando os arquivos
vendas_df = pd.read_csv('Contoso - Vendas - 2017.csv', sep=';')
produtos_df = pd.read_csv('Contoso - Cadastro Produtos.csv', sep=';', encoding='ISO-8859-1')
clientes_df = pd.read_csv('Contoso - Clientes.csv', sep=';', encoding='ISO-8859-1')
lojas_df = pd.read_csv('Contoso - Lojas.csv', sep=';', encoding='ISO-8859-1')

#Renomenando colunas
clientes_df = clientes_df.rename(columns={'ÿID Cliente': 'ID Cliente'})
lojas_df = lojas_df.rename(columns={'ÿID Loja': 'ID Loja'})
produtos_df = produtos_df.rename(columns={'ÿNome do Produto': 'Nome do Produto'})

#limpando apenas as colunas que queremos
clientes_df = clientes_df[['ID Cliente', 'E-mail']]
produtos_df = produtos_df[['ID Produto', 'Nome do Produto']]
lojas_df = lojas_df[['ID Loja', 'Nome da Loja']]

#mesclando e renomeando os dataframes
vendas_df = vendas_df.merge(produtos_df, on='ID Produto')
vendas_df = vendas_df.merge(lojas_df, on='ID Loja')
vendas_df = vendas_df.merge(clientes_df, on='ID Cliente').rename(columns={'E-mail': 'E-mail do Cliente'})
display(vendas_df)

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Nome do Produto,Nome da Loja,E-mail do Cliente
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1,A. Datum Advanced Digital Camera M300 Pink,Loja Contoso Austin,rbrumfieldmy@ameblo.jp
1,2,01/01/2017,06/01/2017,5,308,1586,2,18469,9,1,SV DVD 55DVD Storage Binder M56 Black,Loja Contoso North America Reseller,cshawd4@technorati.com
2,3,01/01/2017,01/01/2017,0,294,1444,5,19730,13,1,"The Phone Company Touch Screen Phones 26-2.2"" ...",Loja Contoso Tehran No.2,kgorriekd@bandcamp.com
3,4,01/01/2017,01/01/2017,0,251,1468,5,29326,6,1,Contoso Touch Screen Phones - CRT M11 Black,Loja Contoso Singapore,angela49@adventure-works.com
4,5,01/01/2017,07/01/2017,6,94,1106,2,22617,4,1,Contoso SLR Camera M146 Orange,Loja Contoso Grand Prairie,jacob4@adventure-works.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
980637,980638,31/12/2017,31/12/2017,0,194,2490,4,10353,120,0,Contoso Rubberized Skin BlackBerry E100 White,Loja Contoso Ridgely,ocrosson9u@illinois.edu
980638,980639,31/12/2017,06/01/2018,6,32,2488,4,31750,120,0,Contoso Rubberized Skin BlackBerry E100 Black,Loja Contoso Milliken,victor11@adventure-works.com
980639,980640,31/12/2017,03/01/2018,3,210,2511,10,12003,80,0,Contoso Original K1m Li-Ion Standard Battery E...,Loja Contoso Cheshire,mtopaz4@gmpg.org
980640,980641,31/12/2017,31/12/2017,0,53,436,4,25550,39,0,Adventure Works Desktop PC1.80 ED180 White,Loja Contoso East Troy,lance5@adventure-works.com
980641,980642,31/12/2017,31/12/2017,0,309,2510,10,28707,80,0,Contoso Original K1m Li-Ion Standard Battery E...,Loja Contoso Europe Reseller,jan8@adventure-works.com

In [ ]:
#agora vamos criar o csv
vendas_df.to_csv('Novo Vnedas 2017.csv', sep=';')
vendas_df.to_csv(r'C:\Users\Kiko\Documents\Projetos Programação\Especializacao-em-Analise-de-Dados\06. Trilha Impressionadora - Especialização em Python\48. Análise de Dados com o Pandas + Integração Python e Excel\Pandas e csv\Novo Vnedas 2017.csv', sep=';')

### Criando um dicionário, transformando o dicionário em um DataFrame e Exportando para csv

In [7]:
vendas_produtos = {'iphone': [558147, 951642], 'galaxy': [712350, 244295], 'ipad': [573823, 26964], 'tv': [405252, 787604], 'máquina de café': [718654, 867660], 'kindle': [531580, 78830], 'geladeira': [973139, 710331], 'adega': [892292, 646016], 'notebook dell': [422760, 694913], 'notebook hp': [154753, 539704], 'notebook asus': [887061, 324831], 'microsoft surface': [438508, 667179], 'webcam': [237467, 295633], 'caixa de som': [489705, 725316], 'microfone': [328311, 644622], 'câmera canon': [591120, 994303]}

vendas_produtos_df = pd.DataFrame.from_dict(vendas_produtos, orient='index')
vendas_produtos_df = vendas_produtos_df.rename(columns={0: 2019})
vendas_produtos_df = vendas_produtos_df.rename(columns={1: 2020})
display(vendas_produtos_df)

vendas_df.to_csv('Novo Vendas Produtos.csv', sep=';', encoding='latin1')

                     2019    2020
iphone             558147  951642
galaxy             712350  244295
ipad               573823   26964
tv                 405252  787604
máquina de café    718654  867660
kindle             531580   78830
geladeira          973139  710331
adega              892292  646016
notebook dell      422760  694913
notebook hp        154753  539704
notebook asus      887061  324831
microsoft surface  438508  667179
webcam             237467  295633
caixa de som       489705  725316
microfone          328311  644622
câmera canon       591120  994303